/* auto generated by create_index.sh */

import TopicsIndexPage from './topics_index_page';
import TopicsNewPage from './topics_new_page';
import TopicsShowPage from './topics_show_page';


export default {
  TopicsIndexPage,
  TopicsNewPage,
  TopicsShowPage,
};
