/* auto generated by create_index.sh */

import TopicsShowPage from './topics_show_page';
import TopicsIndexPage from './topics_index_page';
import TopicsNewPage from './topics_new_page';


export default {
  TopicsShowPage,
  TopicsIndexPage,
  TopicsNewPage,
};
