/* auto generated by create_index.sh */

import AccountsEditPage from './accounts_edit_page';
import AccountsEmailConfirmPage from './accounts_email_confirm_page';
import AccountsEmailSentPage from './accounts_email_sent_page';
import AccountsNewPage from './accounts_new_page';
import App from './app';
import BasePage from './base_page';
import DashboardPage from './dashboard_page';
import DivisionsEditPage from './divisions_edit_page';
import DivisionsNewPage from './divisions_new_page';
import DivisionsShowPage from './divisions_show_page';
import GroupLayout from './group_layout';
import GroupsNewPage from './groups_new_page';
import GroupsShowPage from './groups_show_page';
import SigninRequired from './signin_required';
import ToplevelLayout from './toplevel_layout';
import WelcomePage from './welcome_page';

import Auth from './auth';
import Categories from './categories';
import Divisions from './divisions';
import Groups from './groups';

export default {
  AccountsEditPage,
  AccountsEmailConfirmPage,
  AccountsEmailSentPage,
  AccountsNewPage,
  App,
  BasePage,
  DashboardPage,
  DivisionsEditPage,
  DivisionsNewPage,
  DivisionsShowPage,
  GroupLayout,
  GroupsNewPage,
  GroupsShowPage,
  SigninRequired,
  ToplevelLayout,
  WelcomePage,
  Auth,
  Categories,
  Divisions,
  Groups,
};
