/* auto generated by create_index.sh */

import DevTools from './dev_tools';
import App from './app';
import GroupsShowPage from './groups_show_page';
import DivisionsEditPage from './divisions_edit_page';
import GroupsNewPage from './groups_new_page';
import DivisionsNewPage from './divisions_new_page';
import AccountsNewPage from './accounts_new_page';
import DashboardPage from './dashboard_page';
import DivisionsShowPage from './divisions_show_page';
import Root from './root';

import Auth from './auth';
import Divisions from './divisions';
import Groups from './groups';

export default {
  DevTools,
  App,
  GroupsShowPage,
  DivisionsEditPage,
  GroupsNewPage,
  DivisionsNewPage,
  AccountsNewPage,
  DashboardPage,
  DivisionsShowPage,
  Root,
  Auth,
  Divisions,
  Groups,
};
