#!/usr/bin/env bash

set -ue

source $(dirname $0)/config.sh


function create_index() {
    pushd $1 > /dev/null

    JS_FILES=$(find . -maxdepth 1 -type f -name '*.js' ! -name 'index.js')
    SUB_DIRS=$(find . -maxdepth 1 -type d ! -name '.')

    CLASS_NAMES=""
    {
        echo "/* auto generated by create_index.sh */"
        echo
        for JS_FILE in $JS_FILES; do
            CLASS_NAME=$(basename $JS_FILE .js | Camelize)
            CLASS_NAMES="${CLASS_NAMES}${CLASS_NAME}\n"
            echo "import $CLASS_NAME from './$(basename $JS_FILE .js)';"
        done
        echo
        for SUB_DIR in $SUB_DIRS; do
            CLASS_NAME=$(basename $SUB_DIR | Camelize)
            CLASS_NAMES="${CLASS_NAMES}${CLASS_NAME}\n"
            echo "import $CLASS_NAME from './$(basename $SUB_DIR)';"
        done
        echo
        echo "export default {"
        echo -e $CLASS_NAMES | sed '/^$/d' | sed -e 's|^|  |g' | sed -e 's|$|,|g'
        echo "};"
    } > index.js

    for SUB_DIR in $SUB_DIRS; do
        create_index $SUB_DIR
    done

    popd > /dev/null
}

create_index ${1:-./javascripts/containers}
