/* auto generated by create_index.sh */

import SessionsSignInPage from './sessions_sign_in_page';
import SessionsSignOutPage from './sessions_sign_out_page';


export default {
  SessionsSignInPage,
  SessionsSignOutPage,
};
