/* auto generated by create_index.sh */

import SessionsSignOutPage from './sessions_sign_out_page';
import SessionsSignInPage from './sessions_sign_in_page';


export default {
  SessionsSignOutPage,
  SessionsSignInPage,
};
