version: '2'
services:
  api:
    build: opentie
    command: 'foreman start'
    volumes:
      - '/app/log'
    links:
      - redis
      - postgres
      - kibokan
    depends_on:
      - postgres
    environment:
      - RAILS_ENV=production
      - SERVICE_HOSTURL=http://localhost/
      - REDIS_URL=redis://redis/1
      - DATABASE_URL=postgres://postgres:@postgres/postgres
      - KIBOKAN_HOST=kibokan:8124
  frontend:
#   build: opentie/frontend
    image: opentie/frontend
    ports:
      - '3000:80'
    links:
      - api
  redis:
    restart: always
    image: redis:3.0
    command: 'redis-server --appendonly yes'
  postgres:
    restart: always
    image: postgres:9.4
#   volumes:
#     - :/var/lib/postgresql/data
  kibokan:
    restart: always
    immage: opentie/kibokan
#   build: kibokan-db
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo/opentie
  mongo:
    restart: always
    image: mongo:3.2
#   volumes:
#     - :/data/db
#     - :/data/configdb