/* auto generated by create_index.sh */

import GroupsShowPage from './groups_show_page';
import SubSchemataShowPage from './sub_schemata_show_page';
import GroupsIndexPage from './groups_index_page';
import GroupSchemataEditPage from './group_schemata_edit_page';
import SubSchemataNewPage from './sub_schemata_new_page';
import GroupSchemataIndexPage from './group_schemata_index_page';
import GroupsEditPage from './groups_edit_page';
import GroupSchemataNewPage from './group_schemata_new_page';
import SubSchemataIndexPage from './sub_schemata_index_page';
import SubSchemataEditPage from './sub_schemata_edit_page';
import ChangeLogsIndexPage from './change_logs_index_page';
import GroupSchemataShowPage from './group_schemata_show_page';

import Message from './message';

export default {
  GroupsShowPage,
  SubSchemataShowPage,
  GroupsIndexPage,
  GroupSchemataEditPage,
  SubSchemataNewPage,
  GroupSchemataIndexPage,
  GroupsEditPage,
  GroupSchemataNewPage,
  SubSchemataIndexPage,
  SubSchemataEditPage,
  ChangeLogsIndexPage,
  GroupSchemataShowPage,
  Message,
};
