default: &default
  service_name: "opentie"
  organization_name: "opentie-developper"
  organization_mail: "opentie@sample.com"
  organization_tel: "xxx-xxxx-xxxx"
  kibokan_host: <%= ENV['KIBOKAN_HOST'] %>

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
