default: &default
  service_name: "opentie"
  organization_name: "opentie-developper"
  organization_mail: "opentie@sample.com"
  organization_tel: "xxx-xxxx-xxxx"
  kibokan_host: "127.0.0.1:1234"

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
