/* auto generated by create_index.sh */

import TopicsShowPage from './topics_show_page';
import TopicsNewPage from './topics_new_page';
import LabelsIndexPage from './labels_index_page';
import LabelsNewPage from './labels_new_page';
import LabelsEditPage from './labels_edit_page';
import TopicsIndexPage from './topics_index_page';


export default {
  TopicsShowPage,
  TopicsNewPage,
  LabelsIndexPage,
  LabelsNewPage,
  LabelsEditPage,
  TopicsIndexPage,
};
