/* auto generated by create_index.sh */

import LabelsEditPage from './labels_edit_page';
import LabelsIndexPage from './labels_index_page';
import LabelsNewPage from './labels_new_page';
import TopicsIndexPage from './topics_index_page';
import TopicsNewPage from './topics_new_page';
import TopicsShowPage from './topics_show_page';


export default {
  LabelsEditPage,
  LabelsIndexPage,
  LabelsNewPage,
  TopicsIndexPage,
  TopicsNewPage,
  TopicsShowPage,
};
