/* auto generated by create_index.sh */

import MessageLayout from './message_layout';
import RequestsEditPage from './requests_edit_page';
import RequestsNewPage from './requests_new_page';
import RequestsShowPage from './requests_show_page';
import SchemataIndexPage from './schemata_index_page';
import SchemataShowPage from './schemata_show_page';

import Message from './message';

export default {
  MessageLayout,
  RequestsEditPage,
  RequestsNewPage,
  RequestsShowPage,
  SchemataIndexPage,
  SchemataShowPage,
  Message,
};
