/* auto generated by create_index.sh */

import SubSchemataShowPage from './sub_schemata_show_page';
import SubSchemataIndexPage from './sub_schemata_index_page';
import RequestsNewPage from './requests_new_page';
import RequestsShowPage from './requests_show_page';
import RequestsEditPage from './requests_edit_page';

import Message from './message';

export default {
  SubSchemataShowPage,
  SubSchemataIndexPage,
  RequestsNewPage,
  RequestsShowPage,
  RequestsEditPage,
  Message,
};
